import type React from 'react';

const Hero: React.FC = () => {
  return (
    <div className="py-16">
      <div className="container mx-auto px-4">
        <div className="flex flex-col items-center lg:flex-row">
          <div className="mb-10 w-full lg:mb-0 lg:w-1/2">
            <h1 className="mb-6 text-4xl font-bold leading-tight text-gray-900 md:text-5xl lg:text-6xl">
              Professional AI <br />
              Headshots in minutes.
            </h1>
            <p className="mb-8 text-lg text-gray-600 md:text-xl">
              Elevate your online presence with HD headshots generated by our AI. Ideal for social profiles, resumes, and professional portfolios.
            </p>
            <button className="rounded-full bg-blue-600 px-8 py-3 font-semibold text-white transition duration-300 hover:bg-blue-700">
              Get Your Headshots
            </button>
            <p className="mt-4 text-sm text-gray-500">
              Trusted by professionals worldwide. Quick and efficient.
            </p>
            <p className="mt-4 text-sm">
              Already a member?{' '}
              <a href="/signin" className="text-blue-600 hover:underline">
                Sign In
              </a>
            </p>
          </div>
          <div className="grid w-full grid-cols-2 gap-4 lg:w-1/2">
            <div className="grid gap-4">
              <div className="overflow-hidden rounded-lg">
                <img
                  src="https://res.cloudinary.com/db3xtka1o/image/upload/f_auto/w_300/q_70/tools/tdcr5z6mkpdep1ltioxc"
                  alt="Professional Headshot 1"
                  className="h-full w-full object-cover"
                />
              </div>
              <div className="overflow-hidden rounded-lg">
                <img
                  src="https://res.cloudinary.com/db3xtka1o/image/upload/f_auto/w_300/q_70/tools/tdcr5z6mkpdep1ltioxc"
                  alt="Professional Headshot 2"
                  className="h-full w-full object-cover"
                />
              </div>
            </div>
            <div className="grid gap-4">
              <div className="overflow-hidden rounded-lg">
                <img
                  src="https://res.cloudinary.com/db3xtka1o/image/upload/f_auto/w_300/q_70/tools/tdcr5z6mkpdep1ltioxc"
                  alt="Professional Headshot 3"
                  className="h-full w-full object-cover"
                />
              </div>
              <div className="overflow-hidden rounded-lg">
                <img
                  src="https://res.cloudinary.com/db3xtka1o/image/upload/f_auto/w_300/q_70/tools/tdcr5z6mkpdep1ltioxc"
                  alt="Professional Headshot 4"
                  className="h-full w-full object-cover"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;
