name: Frontend CI/CD (mak-2-ap)

on:
  push:
    branches:
      - feature/mak-2-ap   # Trigger on push to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/makeheadshot-frontend
            git pull origin feature/mak-2-ap
            npm install
            npm run build
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
