name: Frontend Deployment

on:
  push:
    branches:
      - feature/mak-2-ap

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Makeheadshot-Frontend-Final
            git fetch origin
            git checkout feature/mak-2-ap
            git pull --no-rebase origin feature/mak-2-ap
            npm install
            npm run build
            pm2 delete frontend || true
            pm2 start npm --name "frontend" -- start
            pm2 save
